#!/bin/bash

# Creates an html page to easily compare side-by-side the reference targets with the targets generated by the current code (run.sh)

echo '<!DOCTYPE html><html><head><style>'
echo '.row{display: flex}'
echo '.col{width: 50%}'
echo 'img{max-width: 100%}'
echo '</style></head><body>'
for f in `ls out/ref-*colored.svg`; do
  tgt_ref=${f/out\//}
  tgt=${tgt_ref/ref-/}
  echo $tgt
  echo '<div class="row">'
  echo '<div class="col col-ref"><img src="'${tgt_ref}'"></div>'
  echo '<div class="col col-tgt"><img src="'${tgt}'"></div>'
  echo '</div>'

done
echo "</body></html>"
