#
# Richard Eliáš <richard.elias@matfyz.cz>
#

MODULE                  = tree
ROOTDIR                 = ..
RELEASE                 = -O3

include ../module.mk

%:
	make --directory= --file=Makefile ./tree/Makefile

