#
# Richard Eliáš <richard.elias@matfyz.cz>
#

MODULE                  = app
ROOTDIR                 = ..
RELEASE                 = -O3

%:
	make --directory=${ROOTDIR} --file=Makefile $@

include ../module.mk

