#
# File: Makefile.RNAfold
# Created: 2015-04-20 18:55
# By: Richard Eliáš <richard@ba30.eu>
#

SHELL		= /bin/bash
RNAFOLD		= ~/Projects/RocnikovyProjekt/RNAPlot/bin/RNAfold

ARGS		= --noPS
SEQFILE		= 

run:
	cat $(SEQFILE) | $(RNAFOLD) $(ARGS)
